<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find open_critter)/xacro/inertia.xacro"/>

<xacro:macro name="leg" params="name odd parent_link paw *origin">

  <xacro:property name="servo_effort"    value="1.0"/>
  <xacro:property name="servo_velocity"  value="4.0"/>
  <xacro:property name="servo_torque"    value="0.5"/>
  <xacro:property name="servo_reduction" value="10.0"/>

  <xacro:property name="coxa_lower" value="-1.0"/>
  <xacro:property name="coxa_upper" value="1.0"/>

  <xacro:if value="${odd}">
    <xacro:property name="coxa_model"  value="package://open_critter/meshes/collada/coxa_front.dae"/>
    <xacro:property name="tibia_model" value="package://open_critter/meshes/collada/tibia_rear.dae"/>
    <xacro:property name="yaw" value="0"/>
    <xacro:property name="cyaw" value="${-pi/4}"/>
    <xacro:property name="nyaw" value="${pi}"/>
    <xacro:property name="side" value="1.0"/>
    <xacro:property name="servo_x" value="0"/>
    <xacro:property name="tibia_x" value="0.0075"/>
    <xacro:property name="paw_x" value="0.0015"/>

  </xacro:if>
  <xacro:unless value="${odd}"> <!-- EVEN -->
    <xacro:property name="coxa_model" value="package://open_critter/meshes/collada/coxa_rear.dae"/>
    <xacro:property name="tibia_model" value="package://open_critter/meshes/collada/tibia_front.dae"/>
    <xacro:property name="yaw" value="${pi}"/>
    <xacro:property name="cyaw" value="${pi+pi/4}"/>
    <xacro:property name="nyaw" value="0"/>
    <xacro:property name="side" value="-1.0"/>
    <xacro:property name="servo_x" value="-0.005"/>
    <xacro:property name="tibia_x" value="-0.0025"/>
    <xacro:property name="paw_x" value="0.0035"/>

  </xacro:unless>

  <joint name="${name}_base" type="fixed">
    <parent link="${parent_link}"/>
    <child link="${name}_coxa_servo"/>
    <xacro:insert_block name="origin"/>
  </joint>

  <link name="${name}_coxa_servo">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
    <!-- <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </collision> -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.01 0.03"/>
      </geometry>
        <mass value="0.009"/>
        <xacro:box_inertia m="0.009" x="0.02" y="0.01" z="0.03" />
    </inertial>
  </link>

  <joint name="${name}_coxa_joint" type="revolute">
    <parent link="${name}_coxa_servo"/>
    <child link="${name}_coxa_link"/>
    <origin rpy="0 0 ${cyaw}" xyz="-0.005 0 -0.002"/>
    <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="${coxa_lower}" upper="${coxa_upper}"/>
    <axis xyz="0 0 1"/>
  </joint>
  <transmission name="${name}_coxa_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_coxa_joint">
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_coxa_actuator">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <mechanicalReduction>${servo_reduction}</mechanicalReduction>
          <motorTorqueConstant>${servo_torque}</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_coxa_link">
    <visual>
    <origin rpy="0 0 ${yaw}" xyz="${side*0.002} -0.016 0"/>
      <geometry>
        <mesh filename="${coxa_model}"/>
      </geometry>
    </visual>
    <collision>
    <origin rpy="0 0 ${yaw}" xyz="${side*0.002} -0.016 0"/>
      <geometry>
        <mesh filename="${coxa_model}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.04 0.01 0.03"/>
      </geometry>
        <mass value="0.001"/>
        <xacro:box_inertia m="0.001" x="0.04" y="0.01" z="0.03" />
    </inertial>
  </link>
  <gazebo reference="${name}_coxa_link">
    <gravity>true</gravity>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="${name}_femur_servo_to_coxa_joint" type="fixed">
    <parent link="${name}_coxa_link"/>
    <child link="${name}_femur_servo"/>
    <origin rpy="0 0 0" xyz="${side*-0.005} -0.0275 0"/>
  </joint>

  <link name="${name}_femur_servo">
    <visual>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
    <!-- <collision>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </collision> -->
    <inertial>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="0 0 0"/>
      <geometry>
        <box size="0.02 0.01 0.03"/>
      </geometry>
        <mass value="0.009"/>
        <xacro:box_inertia m="0.009" x="0.02" y="0.01" z="0.03" />
    </inertial>
  </link>

  <joint name="${name}_femur_joint" type="revolute">
    <parent link="${name}_femur_servo"/>
    <child link="${name}_femur_link"/>
    <origin rpy="${-pi/8} 0 0" xyz="${servo_x} 0 0.005"/>
    <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="-1.0" upper="1.0"/>
    <axis xyz="${-1*side} 0 0"/>
  </joint>
  <transmission name="${name}_femur_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_femur_joint">
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_femur_actuator">
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>${servo_reduction}</mechanicalReduction>
          <motorTorqueConstant>${servo_torque}</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_femur_link">
    <visual>
    <origin rpy="0 ${nyaw} 0" xyz="0.0025 -0.0275 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/femur.dae"/>
      </geometry>
    </visual>
    <collision>
    <origin rpy="0 ${nyaw} 0" xyz="0.0025 -0.0275 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/femur.dae"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.05 0.01 0.03"/>
      </geometry>
        <mass value="0.002"/>
        <xacro:box_inertia m="0.002" x="0.05" y="0.01" z="0.03" />
    </inertial>
  </link>
  <gazebo reference="${name}_femur_link">
    <gravity>true</gravity>
    <selfCollide>true</selfCollide>
  </gazebo>

  <joint name="${name}_tibia_joint" type="revolute">
    <parent link="${name}_femur_link"/>
    <child link="${name}_tibia_servo"/>
    <origin rpy="${-pi/8} 0 0" xyz="0 -0.055 0"/>
    <limit effort="${servo_effort}" velocity="${servo_velocity}" lower="-1.0" upper="1.0"/>
    <axis xyz="${side} 0 0"/>
    <dynamics friction="0.7"/>
  </joint>
  <transmission name="${name}_tibia_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_tibia_joint">
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_tibia_actuator">
          <!-- <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>${servo_reduction}</mechanicalReduction>
          <motorTorqueConstant>${servo_torque}</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_tibia_servo">
    <visual>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="${side*servo_x} 0 -0.005"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
    <!-- <collision>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="${side*servo_x} 0 -0.005"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </collision> -->
    <inertial>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="${side*servo_x} 0 -0.005"/>
      <geometry>
        <box size="0.02 0.01 0.03"/>
      </geometry>
        <mass value="0.009"/>
        <xacro:box_inertia m="0.009" x="0.02" y="0.01" z="0.03" />
    </inertial>
  </link>

  <joint name="${name}_tibia_servo_to_femur_joint" type="fixed">
    <parent link="${name}_tibia_servo"/>
    <child link="${name}_tibia_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="${name}_tibia_link">
    <visual>
      <origin rpy="0 0 ${nyaw}" xyz="${tibia_x} 0 -0.03"/>
      <geometry>
        <mesh filename="${tibia_model}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 ${nyaw}" xyz="${tibia_x} 0 -0.03"/>
      <geometry>
        <mesh filename="${tibia_model}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.1 0.005 0.005"/>
      </geometry>
        <mass value="0.001"/>
        <xacro:box_inertia m="0.001" x="0.1" y="0.005" z="0.005" />
    </inertial>
  </link>
  <gazebo reference="${name}_tibia_link">
    <mu1 value="5.0"/>
    <mu2 value="0.5"/>
    <kp value="10000000.0" />
    <kd value="1.0" />
    <fdir1 value="1 0 0"/>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
  </gazebo>

  <!-- RUBBER BALL PAW -->
  <xacro:if value="${paw}">

    <joint name="${name}_tibia_paw_joint" type="fixed">
      <parent link="${name}_tibia_link"/>
      <child link="${name}_paw_link"/>
      <origin rpy="0 0 0" xyz="${paw_x} 0 -0.08"/>
    </joint>

    <link name="${name}_paw_link">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.005"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.005"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.005"/>
        </geometry>
          <mass value="0.001"/>
          <xacro:sphere_inertia m="0.001" r="0.005"/>
      </inertial>
    </link>

    <gazebo reference="${name}_paw_link">
      <!-- <gravity>true</gravity>
      <selfCollide>true</selfCollide>
      <mu1>100.0</mu1>
      <mu2>50.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <fdir1>1 0 0</fdir1>
      <maxContacts>1</maxContacts> -->
      <minDepth>0.0002</minDepth>
      <collision name="${name}__paw_link_collision">
        <geometry>
            <sphere>
            <radius>0.005</radius>
        </sphere>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>100000.0</mu>
              <mu2>100000.0</mu2>
            </ode>
            <torsional>
              <coefficient>1000000</coefficient>
              <use_patch_radius>true</use_patch_radius>
              <surface_radius>0.005</surface_radius>
              <patch_radius>0.005</patch_radius>
            </torsional>
          </friction>
        </surface>
        <!-- <surface>
          <friction>
            <torsional>
                <coefficient>10</coefficient>
                <use_patch_radius>true</use_patch_radius>
                <surface_radius>0.1</surface_radius>
                <patch_radius>0.1</patch_radius>
            </torsional>
          </friction>
          <contact>
            <poissons_ratio>0.01</poissons_ratio>
            <elastic_modulus>1e8</elastic_modulus>
          </contact>
        </surface> -->
      </collision>
      <material>Gazebo/Red</material>
    </gazebo>
  </xacro:if>

</xacro:macro>

</robot>
