<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ultimate leg-->

<xacro:macro name="leg" params="name odd parent_link *origin">

  <xacro:if value="${odd}">
    <xacro:property name="coxa_model"  value="package://open_critter/meshes/collada/coxa_front.dae"/>
    <xacro:property name="tibia_model" value="package://open_critter/meshes/collada/tibia_rear.dae"/>
    <xacro:property name="yaw" value="0"/>
    <xacro:property name="nyaw" value="${pi}"/>
    <xacro:property name="coxa_upper" value="0.7"/>
    <xacro:property name="coxa_lower" value="-1.7"/>
    <xacro:property name="side" value="1.0"/>
    <xacro:property name="servo_x" value="0"/>
    <xacro:property name="tibia_x" value="0.0075"/>
  </xacro:if>
  <xacro:unless value="${odd}"> <!-- EVEN -->
    <xacro:property name="coxa_model" value="package://open_critter/meshes/collada/coxa_rear.dae"/>
    <xacro:property name="tibia_model" value="package://open_critter/meshes/collada/tibia_front.dae"/>
    <xacro:property name="yaw" value="${pi}"/>
    <xacro:property name="nyaw" value="0"/>
    <xacro:property name="coxa_upper" value="1.7"/>
    <xacro:property name="coxa_lower" value="-0.7"/>
    <xacro:property name="side" value="-1.0"/>
    <xacro:property name="servo_x" value="-0.005"/>
    <xacro:property name="tibia_x" value="-0.0025"/>
  </xacro:unless>

  <joint name="${name}_coxa_base_joint" type="fixed">
    <parent link="${parent_link}"/>
    <child link="${name}_coxa_servo"/>
    <xacro:insert_block name="origin"/>
  </joint>

  <link name="${name}_coxa_servo">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="${name}_coxa_servo_joint" type="revolute">
    <parent link="${name}_coxa_servo"/>
    <child link="${name}_coxa_link"/>
    <origin rpy="0 0 ${yaw}" xyz="-0.005 0 -0.002"/>
    <limit effort="100" velocity="0.1" lower="${coxa_lower}" upper="${coxa_upper}"/>
    <axis xyz="0 0 1"/>
  </joint>
  <transmission name="${name}_coxa_servo_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_coxa_servo_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_coxa_servo_actuator">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
          <motorTorqueConstant>1</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_coxa_link">
    <visual>
    <origin rpy="0 0 ${yaw}" xyz="${side*0.002} -0.016 0"/>
      <geometry>
        <mesh filename="${coxa_model}"/>
      </geometry>
    </visual>
  </link>

  <joint name="${name}_femur_servo_coxa_joint" type="fixed">
    <parent link="${name}_coxa_link"/>
    <child link="${name}_femur_servo"/>
    <origin rpy="0 0 0" xyz="${side*-0.005} -0.0275 0"/>
  </joint>

  <link name="${name}_femur_servo">
    <visual>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="${name}_femur_servo_joint" type="revolute">
    <parent link="${name}_femur_servo"/>
    <child link="${name}_femur_link"/>
    <origin rpy="0 0 0" xyz="${servo_x} 0 0.005"/>
    <limit effort="100" velocity="0.1" lower="-2.0" upper="0.7"/>
    <axis xyz="1 0 0"/>
  </joint>
  <transmission name="${name}_femur_servo_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_femur_servo_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_femur_servo_actuator">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
          <motorTorqueConstant>1</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_femur_link">
    <visual>
    <origin rpy="0 ${nyaw} 0" xyz="0.0025 -0.0275 0"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/femur.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="${name}_tibia_servo_joint" type="revolute">
    <parent link="${name}_femur_link"/>
    <child link="${name}_tibia_servo"/>
    <origin rpy="0 0 0" xyz="0 -0.055 0"/>
    <limit effort="100" velocity="0.1" lower="-4.0" upper="1.0"/>
    <axis xyz="1 0 0"/>
  </joint>
  <transmission name="${name}_tibia_servo_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_tibia_servo_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_tibia_servo_actuator">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
          <motorTorqueConstant>1</motorTorqueConstant>
      </actuator>
  </transmission>

  <link name="${name}_tibia_servo">
    <visual>
      <origin rpy="0 ${pi/2} ${nyaw}" xyz="${side*servo_x} 0 -0.005"/>
      <geometry>
        <mesh filename="package://open_critter/meshes/collada/servo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="${name}_tibia_servo_femur_joint" type="fixed">
    <parent link="${name}_tibia_servo"/>
    <child link="${name}_tibia_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="${name}_tibia_link">
    <visual>
      <origin rpy="0 0 ${nyaw}" xyz="${tibia_x} 0 -0.03"/>
      <geometry>
        <mesh filename="${tibia_model}"/>
      </geometry>
    </visual>
  </link>

</xacro:macro>

</robot>
