open_critter:

  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
      - front_left_coxa_joint
      - front_right_coxa_joint
      - rear_right_coxa_joint
      - rear_left_coxa_joint
      - front_left_femur_joint
      - front_right_femur_joint
      - rear_right_femur_joint
      - rear_left_femur_joint
      - front_left_tibia_joint
      - front_right_tibia_joint
      - rear_right_tibia_joint
      - rear_left_tibia_joint

    gains:
      front_left_coxa_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      front_right_coxa_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_right_coxa_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_left_coxa_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      front_left_femur_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      front_right_femur_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_right_femur_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_left_femur_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      front_left_tibia_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      front_right_tibia_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_right_tibia_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      rear_left_tibia_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
